# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e65a72c6-06e2-4adb-9ae9-837da297d9ed";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e65a72c6-06e2-4adb-9ae9-837da297d9ed".device = "/dev/disk/by-uuid/e65a72c6-06e2-4adb-9ae9-837da297d9ed";  # root
  boot.initrd.luks.devices."luks-7e8c65c8-74d9-43c5-a191-6d6977007cb3".device = "/dev/disk/by-uuid/7e8c65c8-74d9-43c5-a191-6d6977007cb3";  # swap

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6991-FF2D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-7e8c65c8-74d9-43c5-a191-6d6977007cb3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
